// Copyright (c) Nate McMaster.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.ComponentModel.DataAnnotations;

namespace McMaster.Extensions.CommandLineUtils
{
    internal class BindContext
    {
        /// <summary>
        /// The top-level application generated by the app builder
        /// </summary>
        public CommandLineApplication RootApp { get; set; }

        /// <summary>
        /// The command selected based on input args.
        /// </summary>
        public CommandLineApplication SelectedCommand { get; set; }

        /// <summary>
        /// An instance of the object that matches <see cref="SelectedCommand" />.
        /// </summary>
        public object Target { get; set; }

        /// <summary>
        /// The binding context for the object for the next subcommand, if SelectedCommand != App.
        /// </summary>
        /// <returns></returns>
        public BindContext Child { get; set; }

        /// <summary>
        /// Validation result, if any.
        /// </summary>
        public ValidationResult ValidationResult { get; set; }

        /// <summary>
        /// Get the binding context that matches <see cref="Target" />.
        /// </summary>
        /// <returns>The context.</returns>
        public BindContext GetBottomContext()
        {
            var retVal = this;
            while (retVal?.Child != null)
            {
                retVal = retVal.Child;
            }
            return retVal;
        }
    }
}
