name: Setup .NET
description: Install .NET SDK versions used by this project

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.x
          9.x
          10.x
