name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/*/PublicAPI.*.txt'
      - '.github/workflows/docs.yml'

  pull_request:
    paths:
      - 'docs/**'
      - 'src/*/PublicAPI.*.txt'
      - '.github/workflows/docs.yml'

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/actions/setup-dotnet
    - name: Run docs generation
      run: ./docs/generate.ps1

    - name: Publish docs to GH Pages
      if: github.event_name == 'push'
      run: ./docs/push.ps1 -a ${{ github.token }}
